### ISSUE TITLE
Can't do partial shipments

### ISSUE THREAD

**Issue by emilev79** [DPDBeNeLux/magento-DPD_Shipping#11]
Just noticed. When a customer in Magento orders let's say 5 products and we want to ship 4 of the 5 and send one later this is not possible. We can only fulfill the whole order. This can be a 'showstopper' for us as we have a lot of customers ordering multiple items.

**Comment by teuphil** [comment]
hey, is this still an issue?

we tried the workaround but concluded that this isn't a way we can go.
When creating the first partial shipment we need the first label right then.
If we are shipping the second partial later we can't create the second label with magento
(the problem is that we need the order to not be completed or else this will lead to chaos)
