### ISSUE TITLE
Logo's and buble background not showing on google map

### ISSUE THREAD

**Issue by mvgucht** [DPDBeNeLux/magento-DPD_Shipping#32]
Try removing the max with on lin 109 in file [shipping.js](https://github.com/DPDBeNeLux/magento-DPD_Shipping/blob/master/js/dpd/shipping.js#L108).
109                         maxWidth: “400px”
110         }):
Should become
108         var infowindow = new google.maps.InfoWindow();
And nothing more.

**Comment by oliver-graetz** [comment]
This bug was closed more than a year ago but there is no new release on the website. Why does every user of the extension have to experience this problem again? If they don't find this fix, then they might just uninstall the extension and not use DPD.

**Comment by mvgucht** [comment]
The extension is updated here on github. If you want to use the latest version download the extension from master as a zip and upload it via ftp.

https://github.com/DPDBeNeLux/magento-DPD_Shipping/blob/master/js/dpd/shipping.js#L108

**Comment by oliver-graetz** [comment]
There are no releases at all here on GitHub ("0 releases" in the top area). The master branch should never be used for production use because from a developer viewing point it should be considered as "always broken".

Of course, I can download the master branch as a ZIP and just use that. That was not the point of the comment. The regular user will go to https://www.dpd.com/be/business_customers/customer_tools/e_commerce and then to MagentoConnect and use that version. Then they test it, find that the parcel shops selection doesn't work, then perhaps just uninstall the extension and skip using DPD. This is not the way you want your customers to react.

**Comment by mvgucht** [comment]
Thanks for the feedback, I will look into creating release here on git as you propose. 

I see the master branch as a branch that should always work. Put i see your point.

BTW: the parcelshop selection will never work out of the box, not without a working delisID, password and web service activation (not on by default)
It is hidden automatically when the web service connection fails.

**Comment by oliver-graetz** [comment]
The selection does work for me, the webservice connection is working. The problem is just that when clicking on a shop then in the map just the lower end of the bubble (the marker triangle) is shown but the rest of the bubble include the "Use this shop" link is missing. If the "Show the list of ParcelShops to the right of the map" is not used then the selection proess cannot be completed at all. Removing the `maxWidth` fixes that.
